apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data
spec:
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: "1Gi"
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/postgresql-openalt