apiVersion: v1
kind: Secret
metadata:
  name: postgres-application
type: Opaque
stringData:
  db.user: micro
  db.name: microservice
  db.address: postgresql-service
  db.pass: password
  db.port: "5432"