apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
{{ include "postgresql-openalt.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas | default 1}}
  selector:
    matchLabels:
{{ include "postgresql-openalt.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "postgresql-openalt.labels" . | indent 8 }}
    spec:
      containers: 
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: db.user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: db.pass
        {{- range $envName, $envValue := .Values.envVars }}
        - name: {{ $envName | upper }}
          value: {{ $envValue | quote }}
        {{- end}}
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Release.Name }}-data  
      volumes: 
      - name: {{ .Release.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data
