apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
    name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        name: {{ .Release.Name }}
    spec:
      containers: 
      - name: {{ .Chart.Name }}
        image: postgres:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: db.user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: db.pass
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data  
      volumes: 
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data
