apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ quote .Values.persistence.requests.storage }}