apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data
spec:
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: "8Gi"
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/wfm-postgresql
